## Table of Contents

### 1. Importing libraries
### 2. Importing data
### 3. Grouping data and aggregating variables
##### 1. Aggregate mean of order_number column grouped by department_id
##### 2. Create a loyalty flag
##### 3. Create a spending flag
##### 4. Create an order frequency flag
### 4. Exporting data

# 01. Importing libraries

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

# 02. Importing data

In [2]:
# Create path shortcut
path = r'/Users/taraperrigeold/Documents/Documents - Tara Perrige’s MacBook Pro/CareerFoundry/Instacart Basket Analysis'

In [3]:
# Check output
path

'/Users/taraperrigeold/Documents/Documents - Tara Perrige’s MacBook Pro/CareerFoundry/Instacart Basket Analysis'

In [4]:
# Import orders_products_merged_new_columns.pkl
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged_new_columns.pkl'))

In [5]:
# Check output
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders

In [6]:
# Check shape
ords_prods_merge.shape

(32404859, 18)

# 03. Grouping data and aggregating variables

## 01. Aggregate mean of order_number column grouped by department_id

In [7]:
# Aggregate mean of order_number column grouped by department_id
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

How do these results differ from those of the subset from the exercise?
The means for the entire dataframe seem to be closer together than for the subset; most values are around 15, 16, or 17. Only 3 departments have much higher means: 10, 18, and 21. In the subset, average orders for department 4 (produce) was much higher than for department 17 (household goods), whereas they're much closer after going through the entire dataframe. However, we don't know if any of the differences are statistically significant or not.

## 02. Create a loyalty flag

In [8]:
# Create new max_order column containing the frequency of the order_number column, grouped by user_id
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [9]:
# Check output
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,10

In [10]:
# Check first 100 rows of output
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,8
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,22

In [11]:
# Change options regarding max number of rows to display
pd.options.display.max_rows = None

In [12]:
# Check first 100 rows of output
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,10
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
15,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9
16,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9
17,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,9
18,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,33
19,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,20
20,2231262,31,17,3,11,8.0,196,14,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,20
21,2580647,43,6,4,16,4.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,11
22,2187180,43,9,4,12,3.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,11
23,2497897,52,1,1,9,NaN,196,4,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
24,1318871,52,2,1,10,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
25,1261384,52,3,1,10,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
26,580568,52,5,2,10,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
27,2428073,52,7,2,7,8.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,27
28,342306,52,9,1,11,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
29,1520353,52,10,2,10,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
30,2542086,52,11,2,9,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
31,944694,52,12,1,16,6.0,196,7,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
32,1268191,52,15,2,11,8.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
33,1122089,52,17,2,10,6.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
34,1498922,52,18,2,10,14.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
35,180919,52,19,3,8,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,27
36,2695875,52,21,5,10,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
37,3205960,67,1,3,11,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24
38,970922,67,2,1,15,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
39,596585,67,3,1,13,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
40,2037087,67,4,2,9,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24
41,2474111,67,5,3,14,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24
42,1568481,67,6,3,12,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24
43,2048527,67,8,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24
44,2389031,67,9,2,14,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24
45,2378562,67,10,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
46,1515698,67,11,1,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
47,1928050,67,12,2,12,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24
48,1949274,67,13,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
49,551869,67,14,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
50,768572,67,16,4,10,9.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,24
51,150528,67,18,5,16,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24
52,29758,67,19,0,14,9.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,24
53,1558976,67,21,1,9,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
54,863974,67,22,1,11,14.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
55,2308399,67,23,1,14,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
56,2759128,81,3,1,9,14.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,7
57,1812985,81,5,2,20,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,7
58,1889835,82,1,3,15,NaN,196,6,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,19
59,499460,82,3,5,10,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19
60,2728456,82,4,0,11,16.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,19
61,2653743,82,6,4,9,13.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,19
62,1358880,82,9,1,10,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19
63,343588,82,10,2,11,1.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19
64,3034663,82,15,2,11,12.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19
65,147262,82,18,1,13,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19
66,3144004,82,19,2,15,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19
67,2126069,98,3,0,9,25.0,196,7,0,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,14
68,2210120,98,7,5,14,5.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
69,681011,98,9,3,9,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,14
70,2846344,98,11,4,13,15.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,14
71,747431,98,12,6,13,30.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
72,2383054,98,13,4,11,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,14
73,1993729,98,14,5,8,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,14
74,1403849,109,3,3,17,9.0,196,5,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,6
75,520620,120,1,3,11,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,3
76,3273029,120,3,2,8,19.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,3
77,1861943,185,2,1,12,25.0,196,10,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,6
78,2040988,195,1,1,14,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
79,1680569,195,8,1,9,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
80,276171,195,19,5,11,3.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58
81,2744976,195,22,5,10,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58
82,2781919,195,25,1,14,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
83,1738718,195,31,2,8,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,58
84,3058369,195,34,3,10,6.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,58
85,1485596,195,37,2,15,0.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58
86,417035,195,40,3,16,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,58
87,1615297,195,47,5,10,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58
88,1765587,195,52,3,12,2.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,58
89,745908,195,57,4,11,3.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,58
90,2505656,222,17,2,12,1.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,70
91,3268370,222,38,5,15,1.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,70
92,2016711,290,9,5,19,6.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,51
93,2706088,290,28,6,10,7.0,196,16,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,51
94,1952286,331,6,5,16,30.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,8
95,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,8
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,22

In [13]:
# Create loyalty flag for loyal customers
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [14]:
# Create loyalty flag for regular customers
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [15]:
# Create loyalty flag for new customers
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [16]:
# Check frequency of loyalty_flag column
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [17]:
# Check output, returning first 60 rows of only user_id, loyalty_flag, and order_number columns
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

In [18]:
# Check basic statistics of product prices for each loyalty category
ords_prods_merge.groupby(['loyalty_flag'])['prices'].describe()

,count,mean,std,min,25%,50%,75%,max
loyalty_flag,,,,,,,,
Loyal customer,10284093.0,10.386336,328.017787,1.0,4.2,7.4,11.2,99999.0
New customer,6243990.0,13.294670,597.560299,1.0,4.2,7.4,11.3,99999.0
Regular customer,15876776.0,12.495717,539.720919,1.0,4.2,7.4,11.3,99999.0

The average price of products purchased by loyal customers is lower than for those bought by new customers and regular customers, so it seems that loyal customers buy cheaper products. Also, the standard deviation of the price of products purchased by new customers and regular customers is larger, so it seems that these two categories buy products that fluctuate more in price. However, at this point we don't know if these differences are statistically significant.

## 03. Create a spending flag

In [19]:
# Create new avg_price column containing the average of the prices column, grouped by user_id
ords_prods_merge['avg_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [20]:
# Check output
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_price
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797

In [21]:
# Check first 100 rows of output
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_price
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797
5,3367565,1,6,2,7,19.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797
6,550135,1,7,1,9,20.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
7,3108588,1,8,1,14,14.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
8,2295261,1,9,1,16,0.0,196,4,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
9,2550362,1,10,4,8,30.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
10,2968173,15,15,1,9,7.0,196,2,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556
11,1870022,15,17,2,16,8.0,196,6,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556
12,1911383,15,18,2,11,7.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556
13,2715276,15,21,1,9,7.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556
14,487368,15,22,1,10,14.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556
15,2293453,19,2,5,14,6.0,196,3,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059
16,1973799,19,5,6,12,8.0,196,15,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059
17,532817,19,7,4,17,6.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,9,New customer,8.372059
18,1573906,21,10,3,10,6.0,196,2,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,33,Regular customer,7.012683
19,1593000,31,10,3,8,7.0,196,17,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,20,Regular customer,8.137793
20,2231262,31,17,3,11,8.0,196,14,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,20,Regular customer,8.137793
21,2580647,43,6,4,16,4.0,196,9,0,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898
22,2187180,43,9,4,12,3.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898
23,2497897,52,1,1,9,NaN,196,4,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
24,1318871,52,2,1,10,7.0,196,5,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
25,1261384,52,3,1,10,7.0,196,3,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
26,580568,52,5,2,10,8.0,196,6,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
27,2428073,52,7,2,7,8.0,196,5,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,27,Regular customer,6.356287
28,342306,52,9,1,11,7.0,196,5,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
29,1520353,52,10,2,10,8.0,196,4,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
30,2542086,52,11,2,9,7.0,196,3,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
31,944694,52,12,1,16,6.0,196,7,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
32,1268191,52,15,2,11,8.0,196,3,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
33,1122089,52,17,2,10,6.0,196,4,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
34,1498922,52,18,2,10,14.0,196,6,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
35,180919,52,19,3,8,8.0,196,4,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,27,Regular customer,6.356287
36,2695875,52,21,5,10,30.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
37,3205960,67,1,3,11,NaN,196,1,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790
38,970922,67,2,1,15,5.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
39,596585,67,3,1,13,7.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
40,2037087,67,4,2,9,8.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
41,2474111,67,5,3,14,8.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790
42,1568481,67,6,3,12,7.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790
43,2048527,67,8,2,11,7.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
44,2389031,67,9,2,14,7.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
45,2378562,67,10,1,10,6.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
46,1515698,67,11,1,11,7.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
47,1928050,67,12,2,12,8.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
48,1949274,67,13,1,10,6.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
49,551869,67,14,1,9,7.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
50,768572,67,16,4,10,9.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,24,Regular customer,7.656790
51,150528,67,18,5,16,4.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
52,29758,67,19,0,14,9.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,24,Regular customer,7.656790
53,1558976,67,21,1,9,5.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
54,863974,67,22,1,11,14.0,196,3,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
55,2308399,67,23,1,14,14.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
56,2759128,81,3,1,9,14.0,196,2,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,7,New customer,8.165385
57,1812985,81,5,2,20,30.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,7,New customer,8.165385
58,1889835,82,1,3,15,NaN,196,6,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,19,Regular customer,6.441221
59,499460,82,3,5,10,5.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221
60,2728456,82,4,0,11,16.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,19,Regular customer,6.441221
61,2653743,82,6,4,9,13.0,196,5,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,19,Regular customer,6.441221
62,1358880,82,9,1,10,30.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer,6.441221
63,343588,82,10,2,11,1.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221
64,3034663,82,15,2,11,12.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221
65,147262,82,18,1,13,7.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer,6.441221
66,3144004,82,19,2,15,8.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221
67,2126069,98,3,0,9,25.0,196,7,0,Soda,...,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,14,Regular customer,8.028000
68,2210120,98,7,5,14,5.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14,Regular customer,8.028000
69,681011,98,9,3,9,30.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,14,Regular customer,8.028000
70,2846344,98,11,4,13,15.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,14,Regular customer,8.028000
71,747431,98,12,6,13,30.0,196,4,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14,Regular customer,8.028000
72,2383054,98,13,4,11,30.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,14,Regular customer,8.028000
73,1993729,98,14,5,8,8.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,14,Regular customer,8.028000
74,1403849,109,3,3,17,9.0,196,5,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,6,New customer,5.850725
75,520620,120,1,3,11,NaN,196,2,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,3,New customer,9.385714
76,3273029,120,3,2,8,19.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,3,New customer,9.385714
77,1861943,185,2,1,12,25.0,196,10,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,6,New customer,7.715000
78,2040988,195,1,1,14,NaN,196,2,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730
79,1680569,195,8,1,9,4.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730
80,276171,195,19,5,11,3.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730
81,2744976,195,22,5,10,7.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730
82,2781919,195,25,1,14,4.0,196,1,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730
83,1738718,195,31,2,8,4.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,58,Loyal customer,7.149730
84,3058369,195,34,3,10,6.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer,7.149730
85,1485596,195,37,2,15,0.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730
86,417035,195,40,3,16,2.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer,7.149730
87,1615297,195,47,5,10,2.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730
88,1765587,195,52,3,12,2.0,196,3,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer,7.149730
89,745908,195,57,4,11,3.0,196,3,1,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,58,Loyal customer,7.149730
90,2505656,222,17,2,12,1.0,196,2,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,70,Loyal customer,6.862397
91,3268370,222,38,5,15,1.0,196,6,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,70,Loyal customer,6.862397
92,2016711,290,9,5,19,6.0,196,8,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,51,Loyal customer,7.285597
93,2706088,290,28,6,10,7.0,196,16,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,51,Loyal customer,7.285597
94,1952286,331,6,5,16,30.0,196,8,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,8,New customer,7.705128
95,3226575,360,1,5,12,NaN,196,1,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3,New customer,10.006250
96,1469869,377,3,5,17,3.0,196,9,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3,New customer,8.496552
97,1927023,387,2,4,10,22.0,196,3,0,Soda,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,8,New customer,7.396610
98,858092,420,4,1,19,30.0,196,2,0,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Average orders,22,Regular customer,7.387805
99,119314,420,5,3,19,16.0,196,2,1,Soda,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,22,Regular customer,7.387805

In [22]:
# Create spending flag for low spenders
ords_prods_merge.loc[ords_prods_merge['avg_price'] < 10, 'spending_flag'] = 'Low spender'

In [23]:
# Create spending flag for high spenders
ords_prods_merge.loc[ords_prods_merge['avg_price'] >= 10, 'spending_flag'] = 'High spender'

In [24]:
# Check frequency of spending_flag column
ords_prods_merge['spending_flag'].value_counts(dropna = False)

Low spender     31770742
High spender      634117
Name: spending_flag, dtype: int64

In [25]:
# Check output, returning first 60 rows of only user_id, spending_flag, and avg_price
ords_prods_merge[['user_id', 'spending_flag', 'avg_price']].head(60)

    user_id spending_flag  avg_price
0         1   Low spender   6.367797
1         1   Low spender   6.367797
2         1   Low spender   6.367797
3         1   Low spender   6.367797
4         1   Low spender   6.367797
5         1   Low spender   6.367797
6         1   Low spender   6.367797
7         1   Low spender   6.367797
8         1   Low spender   6.367797
9         1   Low spender   6.367797
10       15   Low spender   3.980556
11       15   Low spender   3.980556
12       15   Low spender   3.980556
13       15   Low spender   3.980556
14       15   Low spender   3.980556
15       19   Low spender   8.372059
16       19   Low spender   8.372059
17       19   Low spender   8.372059
18       21   Low spender   7.012683
19       31   Low spender   8.137793
20       31   Low spender   8.137793
21       43   Low spender   7.444898
22       43   Low spender   7.444898
23       52   Low spender   6.356287
24       52   Low spender   6.356287
25       52   Low spender   6.356287
26       52   Low spender   6.356287
27       52   Low spender   6.356287
28       52   Low spender   6.356287
29       52   Low spender   6.356287
30       52   Low spender   6.356287
31       52   Low spender   6.356287
32       52   Low spender   6.356287
33       52   Low spender   6.356287
34       52   Low spender   6.356287
35       52   Low spender   6.356287
36       52   Low spender   6.356287
37       67   Low spender   7.656790
38       67   Low spender   7.656790
39       67   Low spender   7.656790
40       67   Low spender   7.656790
41       67   Low spender   7.656790
42       67   Low spender   7.656790
43       67   Low spender   7.656790
44       67   Low spender   7.656790
45       67   Low spender   7.656790
46       67   Low spender   7.656790
47       67   Low spender   7.656790
48       67   Low spender   7.656790
49       67   Low spender   7.656790
50       67   Low spender   7.656790
51       67   Low spender   7.656790
52       67   Low spender   7.656790
53       67   Low spender   7.656790
54       67   Low spender   7.656790
55       67   Low spender   7.656790
56       81   Low spender   8.165385
57       81   Low spender   8.165385
58       82   Low spender   6.441221
59       82   Low spender   6.441221

In [26]:
# Check output of first 100 rows containing only user_id, spending_flag, and avg_price
ords_prods_merge[['user_id', 'spending_flag', 'avg_price']].head(100)

    user_id spending_flag  avg_price
0         1   Low spender   6.367797
1         1   Low spender   6.367797
2         1   Low spender   6.367797
3         1   Low spender   6.367797
4         1   Low spender   6.367797
5         1   Low spender   6.367797
6         1   Low spender   6.367797
7         1   Low spender   6.367797
8         1   Low spender   6.367797
9         1   Low spender   6.367797
10       15   Low spender   3.980556
11       15   Low spender   3.980556
12       15   Low spender   3.980556
13       15   Low spender   3.980556
14       15   Low spender   3.980556
15       19   Low spender   8.372059
16       19   Low spender   8.372059
17       19   Low spender   8.372059
18       21   Low spender   7.012683
19       31   Low spender   8.137793
20       31   Low spender   8.137793
21       43   Low spender   7.444898
22       43   Low spender   7.444898
23       52   Low spender   6.356287
24       52   Low spender   6.356287
25       52   Low spender   6.356287
26       52   Low spender   6.356287
27       52   Low spender   6.356287
28       52   Low spender   6.356287
29       52   Low spender   6.356287
30       52   Low spender   6.356287
31       52   Low spender   6.356287
32       52   Low spender   6.356287
33       52   Low spender   6.356287
34       52   Low spender   6.356287
35       52   Low spender   6.356287
36       52   Low spender   6.356287
37       67   Low spender   7.656790
38       67   Low spender   7.656790
39       67   Low spender   7.656790
40       67   Low spender   7.656790
41       67   Low spender   7.656790
42       67   Low spender   7.656790
43       67   Low spender   7.656790
44       67   Low spender   7.656790
45       67   Low spender   7.656790
46       67   Low spender   7.656790
47       67   Low spender   7.656790
48       67   Low spender   7.656790
49       67   Low spender   7.656790
50       67   Low spender   7.656790
51       67   Low spender   7.656790
52       67   Low spender   7.656790
53       67   Low spender   7.656790
54       67   Low spender   7.656790
55       67   Low spender   7.656790
56       81   Low spender   8.165385
57       81   Low spender   8.165385
58       82   Low spender   6.441221
59       82   Low spender   6.441221
60       82   Low spender   6.441221
61       82   Low spender   6.441221
62       82   Low spender   6.441221
63       82   Low spender   6.441221
64       82   Low spender   6.441221
65       82   Low spender   6.441221
66       82   Low spender   6.441221
67       98   Low spender   8.028000
68       98   Low spender   8.028000
69       98   Low spender   8.028000
70       98   Low spender   8.028000
71       98   Low spender   8.028000
72       98   Low spender   8.028000
73       98   Low spender   8.028000
74      109   Low spender   5.850725
75      120   Low spender   9.385714
76      120   Low spender   9.385714
77      185   Low spender   7.715000
78      195   Low spender   7.149730
79      195   Low spender   7.149730
80      195   Low spender   7.149730
81      195   Low spender   7.149730
82      195   Low spender   7.149730
83      195   Low spender   7.149730
84      195   Low spender   7.149730
85      195   Low spender   7.149730
86      195   Low spender   7.149730
87      195   Low spender   7.149730
88      195   Low spender   7.149730
89      195   Low spender   7.149730
90      222   Low spender   6.862397
91      222   Low spender   6.862397
92      290   Low spender   7.285597
93      290   Low spender   7.285597
94      331   Low spender   7.705128
95      360  High spender  10.006250
96      377   Low spender   8.496552
97      387   Low spender   7.396610
98      420   Low spender   7.387805
99      420   Low spender   7.387805

## 04. Create an order frequency flag

In [27]:
# Create new median_days_since_prior_order column containing the median of the days_since_prior_order column, grouped by user_id
ords_prods_merge['median_days_since_prior_order'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [28]:
# Check output
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_price,spending_flag,median_days_since_prior_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.5
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.5

In [29]:
# Check first 100 rows of output
ords_prods_merge.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_price,spending_flag,median_days_since_prior_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.5
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.5
5,3367565,1,6,2,7,19.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5
6,550135,1,7,1,9,20.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
7,3108588,1,8,1,14,14.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
8,2295261,1,9,1,16,0.0,196,4,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
9,2550362,1,10,4,8,30.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5
10,2968173,15,15,1,9,7.0,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
11,1870022,15,17,2,16,8.0,196,6,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,10.0
12,1911383,15,18,2,11,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,10.0
13,2715276,15,21,1,9,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
14,487368,15,22,1,10,14.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
15,2293453,19,2,5,14,6.0,196,3,0,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059,Low spender,6.0
16,1973799,19,5,6,12,8.0,196,15,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059,Low spender,6.0
17,532817,19,7,4,17,6.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Least busy days,Most orders,9,New customer,8.372059,Low spender,6.0
18,1573906,21,10,3,10,6.0,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,33,Regular customer,7.012683,Low spender,7.5
19,1593000,31,10,3,8,7.0,196,17,0,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Average orders,20,Regular customer,8.137793,Low spender,6.0
20,2231262,31,17,3,11,8.0,196,14,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,20,Regular customer,8.137793,Low spender,6.0
21,2580647,43,6,4,16,4.0,196,9,0,Soda,...,both,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898,Low spender,10.0
22,2187180,43,9,4,12,3.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898,Low spender,10.0
23,2497897,52,1,1,9,NaN,196,4,0,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
24,1318871,52,2,1,10,7.0,196,5,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
25,1261384,52,3,1,10,7.0,196,3,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
26,580568,52,5,2,10,8.0,196,6,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
27,2428073,52,7,2,7,8.0,196,5,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,27,Regular customer,6.356287,Low spender,8.0
28,342306,52,9,1,11,7.0,196,5,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
29,1520353,52,10,2,10,8.0,196,4,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
30,2542086,52,11,2,9,7.0,196,3,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
31,944694,52,12,1,16,6.0,196,7,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
32,1268191,52,15,2,11,8.0,196,3,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
33,1122089,52,17,2,10,6.0,196,4,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
34,1498922,52,18,2,10,14.0,196,6,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
35,180919,52,19,3,8,8.0,196,4,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Average orders,27,Regular customer,6.356287,Low spender,8.0
36,2695875,52,21,5,10,30.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
37,3205960,67,1,3,11,NaN,196,1,0,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
38,970922,67,2,1,15,5.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
39,596585,67,3,1,13,7.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
40,2037087,67,4,2,9,8.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
41,2474111,67,5,3,14,8.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
42,1568481,67,6,3,12,7.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
43,2048527,67,8,2,11,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
44,2389031,67,9,2,14,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
45,2378562,67,10,1,10,6.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
46,1515698,67,11,1,11,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
47,1928050,67,12,2,12,8.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
48,1949274,67,13,1,10,6.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
49,551869,67,14,1,9,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
50,768572,67,16,4,10,9.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
51,150528,67,18,5,16,4.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
52,29758,67,19,0,14,9.0,196,2,1,Soda,...,both,Mid-range product,Busiest day,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
53,1558976,67,21,1,9,5.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
54,863974,67,22,1,11,14.0,196,3,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
55,2308399,67,23,1,14,14.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
56,2759128,81,3,1,9,14.0,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,7,New customer,8.165385,Low spender,30.0
57,1812985,81,5,2,20,30.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,7,New customer,8.165385,Low spender,30.0
58,1889835,82,1,3,15,NaN,196,6,0,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,19,Regular customer,6.441221,Low spender,11.5
59,499460,82,3,5,10,5.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender,11.5
60,2728456,82,4,0,11,16.0,196,1,1,Soda,...,both,Mid-range product,Busiest day,Busiest days,Most orders,19,Regular customer,6.441221,Low spender,11.5
61,2653743,82,6,4,9,13.0,196,5,1,Soda,...,both,Mid-range product,Least busy,Least busy days,Most orders,19,Regular customer,6.441221,Low spender,11.5
62,1358880,82,9,1,10,30.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer,6.441221,Low spender,11.5
63,343588,82,10,2,11,1.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender,11.5
64,3034663,82,15,2,11,12.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender,11.5
65,147262,82,18,1,13,7.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer,6.441221,Low spender,11.5
66,3144004,82,19,2,15,8.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender,11.5
67,2126069,98,3,0,9,25.0,196,7,0,Soda,...,both,Mid-range product,Busiest day,Busiest days,Most orders,14,Regular customer,8.028000,Low spender,25.0
68,2210120,98,7,5,14,5.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14,Regular customer,8.028000,Low spender,25.0
69,681011,98,9,3,9,30.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,14,Regular customer,8.028000,Low spender,25.0
70,2846344,98,11,4,13,15.0,196,2,1,Soda,...,both,Mid-range product,Least busy,Least busy days,Most orders,14,Regular customer,8.028000,Low spender,25.0
71,747431,98,12,6,13,30.0,196,4,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14,Regular customer,8.028000,Low spender,25.0
72,2383054,98,13,4,11,30.0,196,1,1,Soda,...,both,Mid-range product,Least busy,Least busy days,Most orders,14,Regular customer,8.028000,Low spender,25.0
73,1993729,98,14,5,8,8.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,14,Regular customer,8.028000,Low spender,25.0
74,1403849,109,3,3,17,9.0,196,5,0,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,6,New customer,5.850725,Low spender,26.0
75,520620,120,1,3,11,NaN,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,3,New customer,9.385714,Low spender,19.0
76,3273029,120,3,2,8,19.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,3,New customer,9.385714,Low spender,19.0
77,1861943,185,2,1,12,25.0,196,10,0,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,6,New customer,7.715000,Low spender,25.0
78,2040988,195,1,1,14,NaN,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
79,1680569,195,8,1,9,4.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
80,276171,195,19,5,11,3.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730,Low spender,4.0
81,2744976,195,22,5,10,7.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730,Low spender,4.0
82,2781919,195,25,1,14,4.0,196,1,1,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
83,1738718,195,31,2,8,4.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,58,Loyal customer,7.149730,Low spender,4.0
84,3058369,195,34,3,10,6.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
85,1485596,195,37,2,15,0.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730,Low spender,4.0
86,417035,195,40,3,16,2.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
87,1615297,195,47,5,10,2.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730,Low spender,4.0
88,1765587,195,52,3,12,2.0,196,3,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
89,745908,195,57,4,11,3.0,196,3,1,Soda,...,both,Mid-range product,Least busy,Least busy days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
90,2505656,222,17,2,12,1.0,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,70,Loyal customer,6.862397,Low spender,5.0
91,3268370,222,38,5,15,1.0,196,6,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,70,Loyal customer,6.862397,Low spender,5.0
92,2016711,290,9,5,19,6.0,196,8,0,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,51,Loyal customer,7.285597,Low spender,7.0
93,2706088,290,28,6,10,7.0,196,16,1,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,51,Loyal customer,7.285597,Low spender,7.0
94,1952286,331,6,5,16,30.0,196,8,0,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,8,New customer,7.705128,Low spender,30.0
95,3226575,360,1,5,12,NaN,196,1,0,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3,New customer,10.006250,High spender,4.0
96,1469869,377,3,5,17,3.0,196,9,0,Soda,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3,New customer,8.496552,Low spender,16.5
97,1927023,387,2,4,10,22.0,196,3,0,Soda,...,both,Mid-range product,Least busy,Least busy days,Most orders,8,New customer,7.396610,Low spender,8.0
98,858092,420,4,1,19,30.0,196,2,0,Soda,...,both,Mid-range product,Regularly busy,Busiest days,Average orders,22,Regular customer,7.387805,Low spender,7.0
99,119314,420,5,3,19,16.0,196,2,1,Soda,...,both,Mid-range product,Regularly busy,Least busy days,Average orders,22,Regular customer,7.387805,Low spender,7.0

In [30]:
# Create order frequency flag for non-frequent customers
ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'

In [31]:
# Create order frequency flag for regular customers
ords_prods_merge.loc[(ords_prods_merge['median_days_since_prior_order'] > 10) & (ords_prods_merge['median_days_since_prior_order'] <= 20), 'order_frequency_flag'] = 'Regular customer'

In [32]:
# Create order frequency flag for frequent customers
ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

In [33]:
# Check frequency of order_frequency_flag column
ords_prods_merge['order_frequency_flag'].value_counts(dropna = False)

Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: order_frequency_flag, dtype: int64

In [34]:
# Check output, returning first 60 rows containing only user_id, order_frequency_flag, and median_days_since_prior_order
ords_prods_merge[['user_id', 'order_frequency_flag', 'median_days_since_prior_order']].head(60)

    user_id   order_frequency_flag  median_days_since_prior_order
0         1  Non-frequent customer                           20.5
1         1  Non-frequent customer                           20.5
2         1  Non-frequent customer                           20.5
3         1  Non-frequent customer                           20.5
4         1  Non-frequent customer                           20.5
5         1  Non-frequent customer                           20.5
6         1  Non-frequent customer                           20.5
7         1  Non-frequent customer                           20.5
8         1  Non-frequent customer                           20.5
9         1  Non-frequent customer                           20.5
10       15      Frequent customer                           10.0
11       15      Frequent customer                           10.0
12       15      Frequent customer                           10.0
13       15      Frequent customer                           10.0
14       15      Frequent customer                           10.0
15       19      Frequent customer                            6.0
16       19      Frequent customer                            6.0
17       19      Frequent customer                            6.0
18       21      Frequent customer                            7.5
19       31      Frequent customer                            6.0
20       31      Frequent customer                            6.0
21       43      Frequent customer                           10.0
22       43      Frequent customer                           10.0
23       52      Frequent customer                            8.0
24       52      Frequent customer                            8.0
25       52      Frequent customer                            8.0
26       52      Frequent customer                            8.0
27       52      Frequent customer                            8.0
28       52      Frequent customer                            8.0
29       52      Frequent customer                            8.0
30       52      Frequent customer                            8.0
31       52      Frequent customer                            8.0
32       52      Frequent customer                            8.0
33       52      Frequent customer                            8.0
34       52      Frequent customer                            8.0
35       52      Frequent customer                            8.0
36       52      Frequent customer                            8.0
37       67      Frequent customer                            7.0
38       67      Frequent customer                            7.0
39       67      Frequent customer                            7.0
40       67      Frequent customer                            7.0
41       67      Frequent customer                            7.0
42       67      Frequent customer                            7.0
43       67      Frequent customer                            7.0
44       67      Frequent customer                            7.0
45       67      Frequent customer                            7.0
46       67      Frequent customer                            7.0
47       67      Frequent customer                            7.0
48       67      Frequent customer                            7.0
49       67      Frequent customer                            7.0
50       67      Frequent customer                            7.0
51       67      Frequent customer                            7.0
52       67      Frequent customer                            7.0
53       67      Frequent customer                            7.0
54       67      Frequent customer                            7.0
55       67      Frequent customer                            7.0
56       81  Non-frequent customer                           30.0
57       81  Non-frequent customer                           30.0
58       82       Regular customer                           11.5
59       82       Regular customer                           11.5

# 04. Exporting data

In [35]:
# Export ords_prods_merge dataframe in pkl format
ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged_grouped.pkl'))